name: OpenWrt Builder ssh

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: main
  REPO_TAG: 24.10.4
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  SSH_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2
      #if: steps.tag.outputs.status == 'success' && !cancelled()
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        #tag_name: ${{ steps.tag.outputs.release_tag }}
        #body_path: release.txt
        #files: ${{ env.FIRMWARE }}/*
        run: echo ${{ github.sha }} > Release.txt
        files: Release.txt
          
